### PR TITLE
Add travis.yml file.

### PR DESCRIPTION
**Pull request by robertzk**

### CODE REVIEW

**Comment by abelcastilloavant** [comment]
Ran tests locally:

```
Testing syberiaMungebits2
discretizer : .......................
drop_percent_missing : .......
....drop_variables()$run : .123
imputer : .........
mungebit_template : ...
new_variable : ..
orderer : ..
remove_outliers : ....
renamer : ........
replace_variable : ..
restore_categorical_variables : .
select_rows()$run : ....
select_variables : .....
value_replacer()$run : ...................

1. Failure (at test-drop_variables.R#10): it correctly drops variables by logical index
iris2 not equal to iris[, c(2, 4)]
Names: 1 string mismatch
Length mismatch: comparison on first 2 components
Component 2: target is NULL, current is numeric

2. Failure (at test-drop_variables.R#15): it correctly drops variables by character index
iris2 not equal to iris[, 3:5]
Names: 1 string mismatch
Component 1: target is NULL, current is numeric

3. Failure (at test-drop_variables.R#20): drops down to a 1-column dataframe, not an atomic vector
iris2 not equal to iris[, 1, drop = FALSE]
Length mismatch: comparison on first 1 components
```

**Comment by robertzk** [comment]
@abelcastilloavant make sure you have latest mungebits2 `devtools::install_github("robertzk/mungebits2")`

**Comment by abelcastilloavant** [comment]
Scrolling through the travis log. This might be relevant: https://travis-ci.org/syberia/syberiaMungebits2/builds/123035356#L2341-L2343

This appears in all 11 test failures:

> "syberiaMungebits2_numeric_to_factor_cpp" not available for .Call() for package "syberiaMungebits2"

**Comment by robertzk** [comment]
Yikes! That is relevant. Will take a closer look - thank you.

**Comment by peterhurford** [comment]
@robertzk @abelcastilloavant LGTM?

**Comment by abelcastilloavant** [comment]
LGTM

**Comment by peterhurford** [comment]
LGTM :+1: :shipit:

**Pull request merged**
